#server configuration
server:
    port: 8082
    #error:
        #include-stacktrace: never

#spring configuration
spring:
    application:
        name: Moneywise

#image configuration size
    servlet: 
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB
#datasource
    datasource:
        url: jdbc:postgresql://localhost:5432/moneywise-db
        username: postgres
        password: Alness0727#
        driver-class-name: org.postgresql.Driver
    jpa: 
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate: 
            ddl-auto: create

#Open api swagger ui 
springdoc: 
    api-docs: 
        path: /api-docs

#prefix endpoints configuration
api:
    prefix: /api 

#secret jwt
#secret: ItSDaNG3r0UsT06oAl0n3TaK3ThIs